receivers:
  opencensus:
    port: 55678

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"

  prometheus:
    namespace: "gopls"
    address: ":8888"

queued-exporters:
  jaeger-all-in-one:
    num-workers: 4
    queue-size: 100
    retry-on-failure: true
    sender-type: jaeger-thrift-http
    jaeger-thrift-http:
      collector-endpoint: http://jaeger-all-in-one:14268/api/traces
      timeout: 5s
